displayName=Spoon Meter
author=djbberko
support=https://github.com/djbberko/spoon-meter
description=Rates how spooned or cursed your account is from collection log KC and uniques
tags=collection,log,luck,drop,rate,spoon,dry,rng,percentile
plugins=com.spoonmeter.SpoonMeterPlugin
build=standard
version=1.0
